server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: processing-group
      enable-auto-commit: false
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"

    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
